model:
  model_type: music-vae
  params:
    lr: 0.001
    kl_weight: 0.2
    use_teacher_forcing: False
    encoder_config:
      input_size: 137
      z_size: 512
      hidden_size: 2048
      num_layers: 1
    decoder_config:
      num_tokens: 137
      z_size: 512
      conductor_in: 512
      conductor_hidden: 1024
      conductor_num_layers: 2
      lstm_hidden: 1024
      lstm_num_layers: 2
      num_subsequences: 2
      notes_per_subsequence: 16

dataloaders:
  validation:
    name: "folk-rnn"
    root: "_data"
    split: "test"
    download: True
    data_type: "tokenized_ABC"
    transforms:
      - folk_rnn:
          sequence_size: 32
    batch_size: 64
    num_workers: 16
    # collate_fn: "pad_collate_single_sequence"

  train:
    - dataset:
        name: "folk-rnn"
        root: "_data"
        split: "train"
        download: True
        data_type: "tokenized_ABC"
        transforms:
          - folk_rnn:
              sequence_size: 32
        batch_size: 64
        num_workers: 16
        # collate_fn: "pad_collate_single_sequence"

lightning:
  trainer:
    benchmark: True
    max_steps: 100000
    # accumulate_grad_batches: 8

callbacks:
  - model_checkpoint:
      filename: "{epoch:06}"
      verbose: True
      save_last: True
  - checkpoint_every_n_steps:
      save_step_frequency: 1000
      prefix: "N-Step-Checkpoint"
      use_modelcheckpoint_filename: False
  - setup_callback:
  - cuda_callback:
