name: wimu
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=2.1.3
  - requests=2.32.3
  - tqdm=4.67.0
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - pip:
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - torchmetrics==1.5.2
      - pytorch-lightning==2.4.0
      - omegaconf==2.3.0
      - music21==9.3.0
      - pypianoroll==1.0.4
      - pretty_midi==0.2.10
      - mido==1.3.3
      - miditok==3.0.4
      - wandb==0.18.6